// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// Flags read by main loop — never call SD/I2S directly from LVGL callbacks
volatile int ui_rec_request = 0;  // 1=start, 2=stop

void on_record_toggle(lv_event_t * e)
{
    static uint32_t last_click = 0;
    uint32_t now = ui_get_millis();
    if (now - last_click < 500) return;
    last_click = now;
    
    ui_log_event("[UI-EV] Mic Clicked -> TOGGLE (3)");
    ui_rec_request = 3; 
}
