// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// Flags read by main loop — never call SD/I2S directly from LVGL callbacks
volatile int ui_rec_request = 0;  // 1=start, 2=stop

void on_record_toggle(lv_event_t * e)
{
    lv_obj_t * btn = lv_event_get_target(e);
    if (lv_obj_has_state(btn, LV_STATE_CHECKED)) {
        ui_rec_request = 1;
    } else {
        ui_rec_request = 2;
    }
}
