// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

void on_record_toggle(lv_event_t * e);
void ui_log_event(const char* msg);
void ui_log_event_v(const char* fmt, ...);
uint32_t ui_get_millis(void); // C bridge for Arduino millis()

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
