// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_arcPulse = NULL;
lv_obj_t * ui_defaultrecord = NULL;
// event funtions
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_defaultrecord(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_record_toggle(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton1 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_forward_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 39);
    lv_obj_set_height(ui_ImgButton1, 48);
    lv_obj_set_x(ui_ImgButton1, 87);
    lv_obj_set_y(ui_ImgButton1, 0);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_arcPulse = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_arcPulse, 100);
    lv_obj_set_height(ui_arcPulse, 100);
    lv_obj_set_align(ui_arcPulse, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arcPulse, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_arcPulse, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_arcPulse, 50);

    lv_obj_set_style_arc_color(ui_arcPulse, lv_color_hex(0x7EFF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcPulse, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcPulse, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_arcPulse, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_defaultrecord = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_defaultrecord, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_voice_png, NULL);
    lv_imgbtn_set_src(ui_defaultrecord, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_stopcircle_png, NULL);
    lv_imgbtn_set_src(ui_defaultrecord, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_stopcircle_png, NULL);
    lv_obj_set_width(ui_defaultrecord, 64);
    lv_obj_set_height(ui_defaultrecord, 64);
    lv_obj_set_align(ui_defaultrecord, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_defaultrecord, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_defaultrecord, ui_event_defaultrecord, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ImgButton1 = NULL;
    ui_arcPulse = NULL;
    ui_defaultrecord = NULL;

}
