// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_panelideas = NULL;
lv_obj_t * ui_labelideas = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
// event funtions
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panelideas = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_panelideas, 240);
    lv_obj_set_height(ui_panelideas, 200);
    lv_obj_set_align(ui_panelideas, LV_ALIGN_CENTER);

    ui_labelideas = lv_label_create(ui_panelideas);
    lv_obj_set_width(ui_labelideas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelideas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelideas, 1);
    lv_obj_set_y(ui_labelideas, -44);
    lv_obj_set_align(ui_labelideas, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_labelideas, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_backward_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 40);
    lv_obj_set_height(ui_ImgButton2, 47);
    lv_obj_set_x(ui_ImgButton2, -101);
    lv_obj_set_y(ui_ImgButton2, 4);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_panelideas = NULL;
    ui_labelideas = NULL;
    ui_ImgButton2 = NULL;

}
